# Dependabot configuration for automatic dependency updates
# See: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # NuGet packages (.NET dependencies)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "chore(nuget)"
      include: "scope"
    # Group updates by type
    groups:
      azure-packages:
        patterns:
          - "Azure.*"
        update-types:
          - "minor"
          - "patch"
      microsoft-packages:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"
      test-packages:
        patterns:
          - "xunit*"
          - "FluentAssertions*"
          - "coverlet*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
