name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  DOTNET_VERSION: "8.0.x"
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker Image
        run: docker build -t issueagent:test .

      - name: Test
        env:
          AZURE_AI_FOUNDRY_ENDPOINT: ${{ secrets.AZURE_AI_FOUNDRY_ENDPOINT }}
          AZURE_AI_FOUNDRY_API_KEY: ${{ secrets.AZURE_AI_FOUNDRY_API_KEY }}
        run: dotnet test --configuration Release --no-build --verbosity normal
