name: Issue Agent
on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  issue-agent:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      id-token: write  # Required for OIDC authentication
    steps:
      - name: Retrieve issue context
        uses: mattdot/issueagent@main
        with:
          github_token: ${{ github.token }}
          azure_ai_foundry_endpoint: ${{ vars.ISSUE_AGENT_ENDPOINT }}
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          enable_verbose_logging: true
          
